exports.seed = async function (knex) {
  await knex('banco').del()
  await knex('banco').insert([
    { bankid: 1, name: 'Banco do Brasil S.A.                                                                      ' },
    { bankid: 3, name: 'BANCO DA AMAZONIA S.A.                                                                    ' },
    { bankid: 4, name: 'Banco do Nordeste do Brasil S.A.                                                          ' },
    { bankid: 7, name: 'BANCO NACIONAL DE DESENVOLVIMENTO ECONOMICO E SOCIAL                                      ' },
    { bankid: 10, name: 'CREDICOAMO CREDITO RURAL COOPERATIVA                                                      ' },
    { bankid: 11, name: 'CREDIT SUISSE HEDGING-GRIFFO CORRETORA DE VALORES S.A                                     ' },
    { bankid: 12, name: 'Banco Inbursa S.A.                                                                        ' },
    { bankid: 14, name: 'STATE STREET BRASIL S.A. - BANCO COMERCIAL                                                ' },
    { bankid: 15, name: 'UBS Brasil Corretora de Câmbio, Títulos e Valores Mobiliários S.A.                        ' },
    { bankid: 16, name: 'COOPERATIVA DE CRÉDITO MÚTUO DOS DESPACHANTES DE TRÂNSITO DE SANTA CATARINA E RI          ' },
    { bankid: 17, name: 'BNY Mellon Banco S.A.                                                                     ' },
    { bankid: 18, name: 'Banco Tricury S.A.                                                                        ' },
    { bankid: 21, name: 'BANESTES S.A. BANCO DO ESTADO DO ESPIRITO SANTO                                           ' },
    { bankid: 24, name: 'Banco Bandepe S.A.                                                                        ' },
    { bankid: 25, name: 'Banco Alfa S.A.                                                                           ' },
    { bankid: 29, name: 'Banco Itaú Consignado S.A.                                                                ' },
    { bankid: 33, name: 'BANCO SANTANDER (BRASIL) S.A.                                                             ' },
    { bankid: 36, name: 'Banco Bradesco BBI S.A.                                                                   ' },
    { bankid: 37, name: 'Banco do Estado do Pará S.A.                                                              ' },
    { bankid: 40, name: 'Banco Cargill S.A.                                                                        ' },
    { bankid: 41, name: 'Banco do Estado do Rio Grande do Sul S.A.                                                 ' },
    { bankid: 47, name: 'Banco do Estado de Sergipe S.A.                                                           ' },
    { bankid: 60, name: 'Confidence Corretora de Câmbio S.A.                                                       ' },
    { bankid: 62, name: 'Hipercard Banco Múltiplo S.A.                                                             ' },
    { bankid: 63, name: 'Banco Bradescard S.A.                                                                     ' },
    { bankid: 64, name: 'GOLDMAN SACHS DO BRASIL BANCO MULTIPLO S.A.                                               ' },
    { bankid: 65, name: 'Banco AndBank (Brasil) S.A.                                                               ' },
    { bankid: 66, name: 'BANCO MORGAN STANLEY S.A.                                                                 ' },
    { bankid: 70, name: 'BRB - BANCO DE BRASILIA S.A.                                                              ' },
    { bankid: 74, name: 'Banco J. Safra S.A.                                                                       ' },
    { bankid: 75, name: 'Banco ABN Amro S.A.                                                                       ' },
    { bankid: 76, name: 'Banco KDB do Brasil S.A.                                                                  ' },
    { bankid: 77, name: 'Banco Inter S.A.                                                                          ' },
    { bankid: 78, name: 'Haitong Banco de Investimento do Brasil S.A.                                              ' },
    { bankid: 79, name: 'Banco Original do Agronegócio S.A.                                                        ' },
    { bankid: 80, name: 'B&T CORRETORA DE CAMBIO LTDA.                                                             ' },
    { bankid: 81, name: 'BancoSeguro S.A.                                                                          ' },
    { bankid: 82, name: 'BANCO TOPÁZIO S.A.                                                                        ' },
    { bankid: 83, name: 'Banco da China Brasil S.A.                                                                ' },
    { bankid: 84, name: 'UNIPRIME DO BRASIL - COOPERATIVA DE CRéDITO LTDA.                                         ' },
    { bankid: 85, name: 'Cooperativa Central de Crédito - Ailos                                                    ' },
    { bankid: 88, name: 'BANCO RANDON S.A.                                                                         ' },
    { bankid: 89, name: 'CREDISAN COOPERATIVA DE CRÉDITO                                                           ' },
    { bankid: 92, name: 'BRK S.A. Crédito, Financiamento e Investimento                                            ' },
    { bankid: 93, name: 'PÓLOCRED SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORT            ' },
    { bankid: 94, name: 'Banco Finaxis S.A.                                                                        ' },
    { bankid: 95, name: 'Travelex Banco de Câmbio S.A.                                                             ' },
    { bankid: 96, name: 'Banco B3 S.A.                                                                             ' },
    { bankid: 97, name: 'Credisis - Central de Cooperativas de Crédito Ltda.                                       ' },
    { bankid: 98, name: 'Credialiança Cooperativa de Crédito Rural                                                 ' },
    { bankid: 99, name: 'UNIPRIME CENTRAL - CENTRAL INTERESTADUAL DE COOPERATIVAS DE CREDITO LTDA.                 ' },
    { bankid: 100, name: 'Planner Corretora de Valores S.A.                                                         ' },
    { bankid: 101, name: 'RENASCENCA DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA                            ' },
    { bankid: 102, name: 'XP INVESTIMENTOS CORRETORA DE CÂMBIO,TÍTULOS E VALORES MOBILIÁRIOS S/A                    ' },
    { bankid: 104, name: 'CAIXA ECONOMICA FEDERAL                                                                   ' },
    { bankid: 105, name: 'Lecca Crédito, Financiamento e Investimento S/A                                           ' },
    { bankid: 107, name: 'Banco Bocom BBM S.A.                                                                      ' },
    { bankid: 108, name: 'PORTOCRED S.A. - CREDITO, FINANCIAMENTO E INVESTIMENTO                                    ' },
    { bankid: 111, name: 'OLIVEIRA TRUST DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIARIOS S.A.                        ' },
    { bankid: 113, name: 'MAGLIANO S.A. CORRETORA DE TÍTULOS E VALORES MOBILIÁRIOS                                  ' },
    { bankid: 114, name: 'Central Cooperativa de Crédito no Estado do Espírito Santo - CECOOP                       ' },
    { bankid: 117, name: 'ADVANCED CORRETORA DE CÂMBIO LTDA                                                         ' },
    { bankid: 119, name: 'Banco Western Union do Brasil S.A.                                                        ' },
    { bankid: 120, name: 'BANCO RODOBENS S.A.                                                                       ' },
    { bankid: 121, name: 'Banco Agibank S.A.                                                                        ' },
    { bankid: 122, name: 'Banco Bradesco BERJ S.A.                                                                  ' },
    { bankid: 124, name: 'Banco Woori Bank do Brasil S.A.                                                           ' },
    { bankid: 125, name: 'BANCO GENIAL S.A.                                                                         ' },
    { bankid: 126, name: 'BR Partners Banco de Investimento S.A.                                                    ' },
    { bankid: 127, name: 'Codepe Corretora de Valores e Câmbio S.A.                                                 ' },
    { bankid: 128, name: 'MS Bank S.A. Banco de Câmbio                                                              ' },
    { bankid: 129, name: 'UBS Brasil Banco de Investimento S.A.                                                     ' },
    { bankid: 130, name: 'CARUANA S.A. - SOCIEDADE DE CRÉDITO, FINANCIAMENTO E INVESTIMENTO                         ' },
    { bankid: 131, name: 'TULLETT PREBON BRASIL CORRETORA DE VALORES E CÂMBIO LTDA                                  ' },
    { bankid: 132, name: 'ICBC do Brasil Banco Múltiplo S.A.                                                        ' },
    { bankid: 133, name: 'CONFEDERAÇÃO NACIONAL DAS COOPERATIVAS CENTRAIS DE CRÉDITO E ECONOMIA FAMILIAR E          ' },
    { bankid: 134, name: 'BGC LIQUIDEZ DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA                          ' },
    { bankid: 136, name: 'CONFEDERAÇÃO NACIONAL DAS COOPERATIVAS CENTRAIS UNICRED LTDA. - UNICRED DO BRASI          ' },
    { bankid: 138, name: 'Get Money Corretora de Câmbio S.A.                                                        ' },
    { bankid: 139, name: 'Intesa Sanpaolo Brasil S.A. - Banco Múltiplo                                              ' },
    { bankid: 140, name: 'NU INVEST CORRETORA DE VALORES S.A.                                                       ' },
    { bankid: 142, name: 'Broker Brasil Corretora de Câmbio Ltda.                                                   ' },
    { bankid: 143, name: 'Treviso Corretora de Câmbio S.A.                                                          ' },
    { bankid: 144, name: 'BEXS BANCO DE CÂMBIO S/A                                                                  ' },
    { bankid: 145, name: 'LEVYCAM - CORRETORA DE CAMBIO E VALORES LTDA.                                             ' },
    { bankid: 146, name: 'GUITTA CORRETORA DE CAMBIO LTDA.                                                          ' },
    { bankid: 149, name: 'Facta Financeira S.A. - Crédito Financiamento e Investimento                              ' },
    { bankid: 157, name: 'ICAP do Brasil Corretora de Títulos e Valores Mobiliários Ltda.                           ' },
    { bankid: 159, name: 'Casa do Crédito S.A. Sociedade de Crédito ao Microempreendedor                            ' },
    { bankid: 163, name: 'Commerzbank Brasil S.A. - Banco Múltiplo                                                  ' },
    { bankid: 173, name: 'BRL Trust Distribuidora de Títulos e Valores Mobiliários S.A.                             ' },
    { bankid: 174, name: 'PEFISA S.A. - CRÉDITO, FINANCIAMENTO E INVESTIMENTO                                       ' },
    { bankid: 177, name: 'Guide Investimentos S.A. Corretora de Valores                                             ' },
    { bankid: 180, name: 'CM CAPITAL MARKETS CORRETORA DE CÂMBIO, TÍTULOS E VALORES MOBILIÁRIOS LTDA                ' },
    { bankid: 183, name: 'SOCRED S.A. - SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO P          ' },
    { bankid: 184, name: 'Banco Itaú BBA S.A.                                                                       ' },
    { bankid: 188, name: 'ATIVA INVESTIMENTOS S.A. CORRETORA DE TÍTULOS, CÂMBIO E VALORES                           ' },
    { bankid: 189, name: 'HS FINANCEIRA S/A CREDITO, FINANCIAMENTO E INVESTIMENTOS                                  ' },
    { bankid: 190, name: 'SERVICOOP - COOPERATIVA DE CRÉDITO DOS SERVIDORES PÚBLICOS ESTADUAIS DO RIO GRAN          ' },
    { bankid: 191, name: 'Nova Futura Corretora de Títulos e Valores Mobiliários Ltda.                              ' },
    { bankid: 194, name: 'PARMETAL DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA                              ' },
    { bankid: 195, name: 'VALOR SOCIEDADE DE CRÉDITO DIRETO S.A.                                                    ' },
    { bankid: 196, name: 'FAIR CORRETORA DE CAMBIO S.A.                                                             ' },
    { bankid: 197, name: 'Stone Pagamentos S.A.                                                                     ' },
    { bankid: 208, name: 'Banco BTG Pactual S.A.                                                                    ' },
    { bankid: 212, name: 'Banco Original S.A.                                                                       ' },
    { bankid: 213, name: 'Banco Arbi S.A.                                                                           ' },
    { bankid: 217, name: 'Banco John Deere S.A.                                                                     ' },
    { bankid: 218, name: 'Banco BS2 S.A.                                                                            ' },
    { bankid: 222, name: 'BANCO CRÉDIT AGRICOLE BRASIL S.A.                                                         ' },
    { bankid: 224, name: 'Banco Fibra S.A.                                                                          ' },
    { bankid: 233, name: 'Banco Cifra S.A.                                                                          ' },
    { bankid: 237, name: 'Banco Bradesco S.A.                                                                       ' },
    { bankid: 241, name: 'BANCO CLASSICO S.A.                                                                       ' },
    { bankid: 243, name: 'BANCO MASTER S/A                                                                          ' },
    { bankid: 246, name: 'Banco ABC Brasil S.A.                                                                     ' },
    { bankid: 249, name: 'Banco Investcred Unibanco S.A.                                                            ' },
    { bankid: 250, name: 'BCV - BANCO DE CRÉDITO E VAREJO S.A.                                                      ' },
    { bankid: 253, name: 'Bexs Corretora de Câmbio S/A                                                              ' },
    { bankid: 254, name: 'PARANÁ BANCO S.A.                                                                         ' },
    { bankid: 259, name: 'MONEYCORP BANCO DE CÂMBIO S.A.                                                            ' },
    { bankid: 260, name: 'NU PAGAMENTOS S.A. - INSTITUIÇÃO DE PAGAMENTO                                             ' },
    { bankid: 265, name: 'Banco Fator S.A.                                                                          ' },
    { bankid: 266, name: 'BANCO CEDULA S.A.                                                                         ' },
    { bankid: 268, name: 'BARI COMPANHIA HIPOTECÁRIA                                                                ' },
    { bankid: 269, name: 'BANCO HSBC S.A.                                                                           ' },
    { bankid: 270, name: 'Sagitur Corretora de Câmbio Ltda.                                                         ' },
    { bankid: 271, name: 'IB Corretora de Câmbio, Títulos e Valores Mobiliários S.A.                                ' },
    { bankid: 272, name: 'AGK CORRETORA DE CAMBIO S.A.                                                              ' },
    { bankid: 273, name: 'Cooperativa de Crédito Rural de São Miguel do Oeste - Sulcredi/São Miguel                 ' },
    { bankid: 274, name: 'MONEY PLUS SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E A EMPRESA DE PEQUENO PORT          ' },
    { bankid: 276, name: 'BANCO SENFF S.A.                                                                          ' },
    { bankid: 278, name: 'Genial Investimentos Corretora de Valores Mobiliários S.A.                                ' },
    { bankid: 279, name: 'COOPERATIVA DE CREDITO RURAL DE PRIMAVERA DO LESTE                                        ' },
    { bankid: 280, name: 'WILL FINANCEIRA S.A. CRÉDITO, FINANCIAMENTO E INVESTIMENTO                                ' },
    { bankid: 281, name: 'Cooperativa de Crédito Rural Coopavel                                                     ' },
    { bankid: 283, name: 'RB INVESTIMENTOS DISTRIBUIDORA DE TITULOS E VALORES MOBILIARIOS LIMITADA                  ' },
    { bankid: 285, name: 'Frente Corretora de Câmbio Ltda.                                                          ' },
    { bankid: 286, name: 'COOPERATIVA DE CRÉDITO RURAL DE OURO SULCREDI/OURO                                        ' },
    { bankid: 288, name: 'CAROL DISTRIBUIDORA DE TITULOS E VALORES MOBILIARIOS LTDA.                                ' },
    { bankid: 289, name: 'DECYSEO CORRETORA DE CAMBIO LTDA.                                                         ' },
    { bankid: 290, name: 'Pagseguro Internet S.A.                                                                   ' },
    { bankid: 292, name: 'BS2 Distribuidora de Títulos e Valores Mobiliários S.A.                                   ' },
    { bankid: 293, name: 'Lastro RDV Distribuidora de Títulos e Valores Mobiliários Ltda.                           ' },
    { bankid: 296, name: 'VISION S.A. CORRETORA DE CAMBIO                                                           ' },
    { bankid: 299, name: 'BANCO SOROCRED S.A. - BANCO MÚLTIPLO                                                      ' },
    { bankid: 300, name: 'Banco de la Nacion Argentina                                                              ' },
    { bankid: 301, name: 'BPP Instituição de Pagamento S.A.                                                         ' },
    { bankid: 306, name: 'PORTOPAR DISTRIBUIDORA DE TITULOS E VALORES MOBILIARIOS LTDA.                             ' },
    { bankid: 307, name: 'Terra Investimentos Distribuidora de Títulos e Valores Mobiliários Ltda.                  ' },
    { bankid: 309, name: 'CAMBIONET CORRETORA DE CÂMBIO LTDA.                                                       ' },
    { bankid: 310, name: 'VORTX DISTRIBUIDORA DE TITULOS E VALORES MOBILIARIOS LTDA.                                ' },
    { bankid: 311, name: 'DOURADA CORRETORA DE CÂMBIO LTDA.                                                         ' },
    { bankid: 312, name: 'HSCM - SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORTE LT          ' },
    { bankid: 313, name: 'AMAZÔNIA CORRETORA DE CÂMBIO LTDA.                                                        ' },
    { bankid: 315, name: 'PI Distribuidora de Títulos e Valores Mobiliários S.A.                                    ' },
    { bankid: 318, name: 'Banco BMG S.A.                                                                            ' },
    { bankid: 319, name: 'OM DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA                                    ' },
    { bankid: 320, name: 'China Construction Bank (Brasil) Banco Múltiplo S/A                                       ' },
    { bankid: 321, name: 'CREFAZ SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E A EMPRESA DE PEQUENO PORTE LT          ' },
    { bankid: 322, name: 'Cooperativa de Crédito Rural de Abelardo Luz - Sulcredi/Crediluz                          ' },
    { bankid: 323, name: 'MERCADOPAGO.COM REPRESENTACOES LTDA.                                                      ' },
    { bankid: 324, name: 'CARTOS SOCIEDADE DE CRÉDITO DIRETO S.A.                                                   ' },
    { bankid: 325, name: 'Órama Distribuidora de Títulos e Valores Mobiliários S.A.                                 ' },
    { bankid: 326, name: 'PARATI - CREDITO, FINANCIAMENTO E INVESTIMENTO S.A.                                       ' },
    { bankid: 328, name: 'COOPERATIVA DE ECONOMIA E CRÉDITO MÚTUO DOS FABRICANTES DE CALÇADOS DE SAPIRANGA          ' },
    { bankid: 329, name: 'QI Sociedade de Crédito Direto S.A.                                                       ' },
    { bankid: 330, name: 'BANCO BARI DE INVESTIMENTOS E FINANCIAMENTOS S.A.                                         ' },
    { bankid: 331, name: 'Fram Capital Distribuidora de Títulos e Valores Mobiliários S.A.                          ' },
    { bankid: 332, name: 'Acesso Soluções de Pagamento S.A.                                                         ' },
    { bankid: 335, name: 'Banco Digio S.A.                                                                          ' },
    { bankid: 336, name: 'Banco C6 S.A.                                                                             ' },
    { bankid: 340, name: 'Super Pagamentos e Administração de Meios Eletrônicos S.A.                                ' },
    { bankid: 341, name: 'ITAÚ UNIBANCO S.A.                                                                        ' },
    { bankid: 342, name: 'Creditas Sociedade de Crédito Direto S.A.                                                 ' },
    { bankid: 343, name: 'FFA SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORTE LTDA.          ' },
    { bankid: 348, name: 'Banco XP S.A.                                                                             ' },
    { bankid: 349, name: 'AL5 S.A. CRÉDITO, FINANCIAMENTO E INVESTIMENTO                                            ' },
    { bankid: 350, name: 'COOPERATIVA DE CRÉDITO RURAL DE PEQUENOS AGRICULTORES E DA REFORMA AGRÁRIA DO CE          ' },
    { bankid: 352, name: 'TORO CORRETORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.                                      ' },
    { bankid: 354, name: 'NECTON INVESTIMENTOS S.A. CORRETORA DE VALORES MOBILIÁRIOS E COMMODITIES                  ' },
    { bankid: 355, name: 'ÓTIMO SOCIEDADE DE CRÉDITO DIRETO S.A.                                                    ' },
    { bankid: 358, name: 'MIDWAY S.A. - CRÉDITO, FINANCIAMENTO E INVESTIMENTO                                       ' },
    { bankid: 359, name: 'ZEMA CRÉDITO, FINANCIAMENTO E INVESTIMENTO S/A                                            ' },
    { bankid: 360, name: 'TRINUS CAPITAL DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.                        ' },
    { bankid: 362, name: 'CIELO S.A.                                                                                ' },
    { bankid: 363, name: 'SINGULARE CORRETORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.                                 ' },
    { bankid: 364, name: 'GERENCIANET S.A.                                                                          ' },
    { bankid: 365, name: 'SIMPAUL CORRETORA DE CAMBIO E VALORES MOBILIARIOS S.A.                                    ' },
    { bankid: 366, name: 'BANCO SOCIETE GENERALE BRASIL S.A.                                                        ' },
    { bankid: 367, name: 'VITREO DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.                                ' },
    { bankid: 368, name: 'Banco CSF S.A.                                                                            ' },
    { bankid: 370, name: 'Banco Mizuho do Brasil S.A.                                                               ' },
    { bankid: 371, name: 'WARREN CORRETORA DE VALORES MOBILIÁRIOS E CÂMBIO LTDA.                                    ' },
    { bankid: 373, name: 'UP.P SOCIEDADE DE EMPRÉSTIMO ENTRE PESSOAS S.A.                                           ' },
    { bankid: 374, name: 'REALIZE CRÉDITO, FINANCIAMENTO E INVESTIMENTO S.A.                                        ' },
    { bankid: 376, name: 'BANCO J.P. MORGAN S.A.                                                                    ' },
    { bankid: 377, name: 'BMS SOCIEDADE DE CRÉDITO DIRETO S.A.                                                      ' },
    { bankid: 378, name: 'BBC LEASING S.A. - ARRENDAMENTO MERCANTIL                                                 ' },
    { bankid: 379, name: 'COOPERFORTE - COOPERATIVA DE ECONOMIA E CRÉDITO MÚTUO DE FUNCIONÁRIOS DE INSTITU          ' },
    { bankid: 380, name: 'PICPAY INSTITUIçãO DE PAGAMENTO S.A.                                                      ' },
    { bankid: 381, name: 'BANCO MERCEDES-BENZ DO BRASIL S.A.                                                        ' },
    { bankid: 382, name: 'FIDÚCIA SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORTE L          ' },
    { bankid: 383, name: 'EBANX INSTITUICAO DE PAGAMENTOS LTDA.                                                     ' },
    { bankid: 384, name: 'GLOBAL FINANÇAS SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO          ' },
    { bankid: 386, name: 'NU FINANCEIRA S.A. - Sociedade de Crédito, Financiamento e Investimento                   ' },
    { bankid: 387, name: 'Banco Toyota do Brasil S.A.                                                               ' },
    { bankid: 389, name: 'Banco Mercantil do Brasil S.A.                                                            ' },
    { bankid: 390, name: 'BANCO GM S.A.                                                                             ' },
    { bankid: 391, name: 'COOPERATIVA DE CREDITO RURAL DE IBIAM - SULCREDI/IBIAM                                    ' },
    { bankid: 393, name: 'Banco Volkswagen S.A.                                                                     ' },
    { bankid: 394, name: 'Banco Bradesco Financiamentos S.A.                                                        ' },
    { bankid: 396, name: 'HUB PAGAMENTOS S.A                                                                        ' },
    { bankid: 397, name: 'LISTO SOCIEDADE DE CREDITO DIRETO S.A.                                                    ' },
    { bankid: 398, name: 'IDEAL CORRETORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.                                     ' },
    { bankid: 399, name: 'Kirton Bank S.A. - Banco Múltiplo                                                         ' },
    { bankid: 400, name: 'COOPERATIVA DE CRÉDITO, POUPANÇA E SERVIÇOS FINANCEIROS DO CENTRO OESTE - CREDIT          ' },
    { bankid: 401, name: 'IUGU INSTITUIÇÃO DE PAGAMENTO S.A.                                                        ' },
    { bankid: 402, name: 'COBUCCIO SOCIEDADE DE CRÉDITO DIRETO S.A.                                                 ' },
    { bankid: 403, name: 'CORA SOCIEDADE DE CRÉDITO DIRETO S.A.                                                     ' },
    { bankid: 404, name: 'SUMUP SOCIEDADE DE CRÉDITO DIRETO S.A.                                                    ' },
    { bankid: 406, name: 'ACCREDITO - SOCIEDADE DE CRÉDITO DIRETO S.A.                                              ' },
    { bankid: 407, name: 'ÍNDIGO INVESTIMENTOS DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.                 ' },
    { bankid: 408, name: 'BONUSPAGO SOCIEDADE DE CRÉDITO DIRETO S.A.                                                ' },
    { bankid: 410, name: 'PLANNER SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR S.A.                                    ' },
    { bankid: 411, name: 'Via Certa Financiadora S.A. - Crédito, Financiamento e Investimentos                      ' },
    { bankid: 412, name: 'BANCO CAPITAL S.A.                                                                        ' },
    { bankid: 413, name: 'BANCO BV S.A.                                                                             ' },
    { bankid: 414, name: 'WORK SOCIEDADE DE CRÉDITO DIRETO S.A.                                                     ' },
    { bankid: 416, name: 'LAMARA SOCIEDADE DE CRÉDITO DIRETO S.A.                                                   ' },
    { bankid: 418, name: 'ZIPDIN SOLUÇÕES DIGITAIS SOCIEDADE DE CRÉDITO DIRETO S/A                                  ' },
    { bankid: 419, name: 'NUMBRS SOCIEDADE DE CRÉDITO DIRETO S.A.                                                   ' },
    { bankid: 421, name: 'LAR COOPERATIVA DE CRÉDITO - LAR CREDI                                                    ' },
    { bankid: 422, name: 'Banco Safra S.A.                                                                          ' },
    { bankid: 423, name: 'COLUNA S/A DISTRIBUIDORA DE TITULOS E VALORES MOBILIÁRIOS                                 ' },
    { bankid: 425, name: 'SOCINAL S.A. - CRÉDITO, FINANCIAMENTO E INVESTIMENTO                                      ' },
    { bankid: 426, name: 'Biorc Financeira - Crédito, Financiamento e Investimento S.A.                             ' },
    { bankid: 427, name: 'COOPERATIVA DE CREDITO DOS SERVIDORES DA UNIVERSIDADE FEDERAL DO ESPIRITO SANTO           ' },
    { bankid: 428, name: 'CRED-SYSTEM SOCIEDADE DE CRÉDITO DIRETO S.A.                                              ' },
    { bankid: 429, name: 'Crediare S.A. - Crédito, financiamento e investimento                                     ' },
    { bankid: 430, name: 'COOPERATIVA DE CREDITO RURAL SEARA - CREDISEARA                                           ' },
    { bankid: 433, name: 'BR-CAPITAL DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.                            ' },
    { bankid: 435, name: 'DELCRED SOCIEDADE DE CRÉDITO DIRETO S.A.                                                  ' },
    { bankid: 438, name: 'PLANNER TRUSTEE DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.                      ' },
    { bankid: 439, name: 'ID CORRETORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.                                        ' },
    { bankid: 440, name: 'CREDIBRF - COOPERATIVA DE CRÉDITO                                                         ' },
    { bankid: 442, name: 'MAGNETIS - DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA                            ' },
    { bankid: 443, name: 'CREDIHOME SOCIEDADE DE CRÉDITO DIRETO S.A.                                                ' },
    { bankid: 444, name: 'TRINUS SOCIEDADE DE CRÉDITO DIRETO S.A.                                                   ' },
    { bankid: 445, name: 'PLANTAE S.A. - CRÉDITO, FINANCIAMENTO E INVESTIMENTO                                      ' },
    { bankid: 447, name: 'MIRAE ASSET WEALTH MANAGEMENT (BRAZIL) CORRETORA DE CÂMBIO, TÍTULOS E VALORES MO          ' },
    { bankid: 448, name: 'HEMERA DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.                               ' },
    { bankid: 449, name: 'DMCARD SOCIEDADE DE CRÉDITO DIRETO S.A.                                                   ' },
    { bankid: 450, name: 'FITBANK PAGAMENTOS ELETRONICOS S.A.                                                       ' },
    { bankid: 452, name: 'CREDIFIT SOCIEDADE DE CRÉDITO DIRETO S.A.                                                 ' },
    { bankid: 454, name: 'MÉRITO DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.                               ' },
    { bankid: 456, name: 'Banco MUFG Brasil S.A.                                                                    ' },
    { bankid: 457, name: 'UY3 SOCIEDADE DE CRÉDITO DIRETO S/A                                                       ' },
    { bankid: 458, name: 'HEDGE INVESTMENTS DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.                    ' },
    { bankid: 459, name: 'COOPERATIVA DE CRÉDITO MÚTUO DE SERVIDORES PÚBLICOS DO ESTADO DE SÃO PAULO - CRE          ' },
    { bankid: 461, name: 'ASAAS GESTÃO FINANCEIRA INSTITUIÇÃO DE PAGAMENTO S.A.                                     ' },
    { bankid: 462, name: 'STARK SOCIEDADE DE CRÉDITO DIRETO S.A.                                                    ' },
    { bankid: 464, name: 'Banco Sumitomo Mitsui Brasileiro S.A.                                                     ' },
    { bankid: 465, name: 'CAPITAL CONSIG SOCIEDADE DE CRÉDITO DIRETO S.A.                                           ' },
    { bankid: 467, name: 'MASTER S/A CORRETORA DE CâMBIO, TíTULOS E VALORES MOBILIáRIOS                             ' },
    { bankid: 473, name: 'Banco Caixa Geral - Brasil S.A.                                                           ' },
    { bankid: 477, name: 'Citibank N.A.                                                                             ' },
    { bankid: 479, name: 'Banco ItauBank S.A.                                                                       ' },
    { bankid: 487, name: 'DEUTSCHE BANK S.A. - BANCO ALEMAO                                                         ' },
    { bankid: 488, name: 'JPMorgan Chase Bank, National Association                                                 ' },
    { bankid: 492, name: 'ING Bank N.V.                                                                             ' },
    { bankid: 495, name: 'Banco de La Provincia de Buenos Aires                                                     ' },
    { bankid: 505, name: 'Banco Credit Suisse (Brasil) S.A.                                                         ' },
    { bankid: 545, name: 'SENSO CORRETORA DE CAMBIO E VALORES MOBILIARIOS S.A                                       ' },
    { bankid: 600, name: 'Banco Luso Brasileiro S.A.                                                                ' },
    { bankid: 604, name: 'Banco Industrial do Brasil S.A.                                                           ' },
    { bankid: 610, name: 'Banco VR S.A.                                                                             ' },
    { bankid: 611, name: 'Banco Paulista S.A.                                                                       ' },
    { bankid: 612, name: 'Banco Guanabara S.A.                                                                      ' },
    { bankid: 613, name: 'Omni Banco S.A.                                                                           ' },
    { bankid: 623, name: 'Banco Pan S.A.                                                                            ' },
    { bankid: 626, name: 'BANCO C6 CONSIGNADO S.A.                                                                  ' },
    { bankid: 630, name: 'BANCO LETSBANK S.A.                                                                       ' },
    { bankid: 633, name: 'Banco Rendimento S.A.                                                                     ' },
    { bankid: 634, name: 'BANCO TRIANGULO S.A.                                                                      ' },
    { bankid: 637, name: 'BANCO SOFISA S.A.                                                                         ' },
    { bankid: 643, name: 'Banco Pine S.A.                                                                           ' },
    { bankid: 652, name: 'Itaú Unibanco Holding S.A.                                                                ' },
    { bankid: 653, name: 'BANCO VOITER S.A.                                                                         ' },
    { bankid: 654, name: 'BANCO DIGIMAIS S.A.                                                                       ' },
    { bankid: 655, name: 'Banco Votorantim S.A.                                                                     ' },
    { bankid: 707, name: 'Banco Daycoval S.A.                                                                       ' },
    { bankid: 712, name: 'Banco Ourinvest S.A.                                                                      ' },
    { bankid: 720, name: 'BANCO RNX S.A.                                                                            ' },
    { bankid: 739, name: 'Banco Cetelem S.A.                                                                        ' },
    { bankid: 741, name: 'BANCO RIBEIRAO PRETO S.A.                                                                 ' },
    { bankid: 743, name: 'Banco Semear S.A.                                                                         ' },
    { bankid: 745, name: 'Banco Citibank S.A.                                                                       ' },
    { bankid: 746, name: 'Banco Modal S.A.                                                                          ' },
    { bankid: 747, name: 'Banco Rabobank International Brasil S.A.                                                  ' },
    { bankid: 748, name: 'BANCO COOPERATIVO SICREDI S.A.                                                            ' },
    { bankid: 751, name: 'Scotiabank Brasil S.A. Banco Múltiplo                                                     ' },
    { bankid: 752, name: 'Banco BNP Paribas Brasil S.A.                                                             ' },
    { bankid: 753, name: 'Novo Banco Continental S.A. - Banco Múltiplo                                              ' },
    { bankid: 754, name: 'Banco Sistema S.A.                                                                        ' },
    { bankid: 755, name: 'Bank of America Merrill Lynch Banco Múltiplo S.A.                                         ' },
    { bankid: 756, name: 'BANCO COOPERATIVO SICOOB S.A. - BANCO SICOOB                                              ' },
    { bankid: 757, name: 'BANCO KEB HANA DO BRASIL S.A.                                                             ' },
  ]);
};